settings:
  title: 'Syntafin.dev Status'
  url: 'https://status.syntafin.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: xivdata-api # unique identifier
    name: XIVDATA API
    description: 'API for XIVDATA' # default=empty
    url: 'https://api.xivdata.com/health_check' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: dotdev-api
    name: Syntafin.dev API
    description: 'API for DotDev, DotSexy and more'
    url: 'https://api.syntafin.dev/healthcheck'
    method: GET
    expectStatus: 200
